### ISSUE TITLE
Wrong number of parameters in model table (?)

### ISSUE THREAD

**Issue by marksverdhei** [ScandEval/scandeval.com#9]
Hi. 
It seems that the parameter counts for the models are off.
For instance, the Llama-2-7b model only has 262 million trainable parameters, whet it should have around 7000
![image](https://github.com/ScandEval/scandeval.github.io/assets/46672778/2534cddb-6c82-42df-9126-a5db29a319a8)

**Comment by saattrupdan** [comment]
Thanks for your feedback! Yeah you're right. I agree that it's misleading. This is currently due to 2 things:

1. I load in large generative models in 4bit quantisation, which makes the total number of parameters less (for LLaMA-7B this becomes about 3.5B parameters).
2. Currently only the trainable parameters are included, which when loading in 4bit is reduced even further, to the 262M parameters you see on the benchmark.

(2) has been fixed on the main branch now (https://github.com/saattrupdan/ScandEval/commit/847d143185909e35c335bff21a43e692aa9d83e8) and will be included in the next `scandeval` release (and I'll update the leaderboard).

As for (1) it's a bit more complicated. One solution could be to utilise the new safetensors format, which allows reading off the number of parameters without loading in the entire model. This requires all these large models to be in this format however, so it's not exactly ideal. But I'll at least get the current leaderboard updated in this way asap.

**Comment by saattrupdan** [comment]
Hi @marksverdhei. Just to let you know that I've now updated the way we fetch the number of parameters, and we now use the safetensors values directly:

https://scandeval.com/
